/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OgRouteImport } from './routes/og'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IFileRouteImport } from './routes/i/$file'
import { Route as ApiUploadRouteImport } from './routes/api/upload'

const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IFileRoute = IFileRouteImport.update({
  id: '/i/$file',
  path: '/i/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/api/upload': typeof ApiUploadRoute
  '/i/$file': typeof IFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/api/upload': typeof ApiUploadRoute
  '/i/$file': typeof IFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/api/upload': typeof ApiUploadRoute
  '/i/$file': typeof IFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/og' | '/api/upload' | '/i/$file'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/og' | '/api/upload' | '/i/$file'
  id: '__root__' | '/' | '/og' | '/api/upload' | '/i/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OgRoute: typeof OgRoute
  ApiUploadRoute: typeof ApiUploadRoute
  IFileRoute: typeof IFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$file': {
      id: '/i/$file'
      path: '/i/$file'
      fullPath: '/i/$file'
      preLoaderRoute: typeof IFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OgRoute: OgRoute,
  ApiUploadRoute: ApiUploadRoute,
  IFileRoute: IFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
